  - name: Write the new ec2 instance host key to known hosts
    connection: local
    shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

- name: "Move backend files to server."
  copy:
    src: /root/project/backend_artifact.tar.gz
    dest: ~/

- name: "Install package dependencies"
  shell: |
    cd ~/backend
    tar -xzvf backend_artifact.tar.gz -C backend
    rm backend_artifact.tar.gz
    cd backend/
    npm run build
    cd dist
    pm2 start npm --name backend -- start